In [108]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as st
import yaml
import functions
%matplotlib inline

try:
    with open("../config.yaml", "r") as file:
        config = yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")

In [109]:
df_stat = pd.read_csv("../data/clean/df_footprints_transformed_client_merged_New.csv")
df_stat = df_stat.drop("treament_group", axis=1)

In [110]:
df_eda = df_stat.copy()

In [ ]:
# df_stat.groupby('client_id').filter(functions.has_all_treatment_groups)

1. Completion rate

In [96]:
df_test = df_stat[df_stat["treatment_group"] == "Test"]
df_test["client_id"].nunique()

25439

In [97]:
df_control = df_stat[df_stat["treatment_group"] == "Control"]
df_control["client_id"].nunique()

21112

In [ ]:
df_stat

In [111]:
df_complete_group = df_stat.groupby(['client_id', 'visitor_id', 'visit_id']).filter(functions.has_all_steps)
df_complete_group

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative,time_diff_percent,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,client_age_group
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0.0,0.0,0.00,3,46,29,U,2,25454.66,2,6,young/adult
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,7.0,7.0,0.04,3,46,29,U,2,25454.66,2,6,young/adult
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,39.0,32.0,0.25,3,46,29,U,2,25454.66,2,6,young/adult
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,138.0,99.0,0.87,3,46,29,U,2,25454.66,2,6,young/adult
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,158.0,20.0,1.00,3,46,29,U,2,25454.66,2,6,young/adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305732,9999729,834634258_21862004160,870243567_56915814033_814203,start,2017-05-08 16:08:25,Test,0.0,0.0,0.00,10,124,31,F,3,107059.74,6,9,young/adult
305733,9999729,834634258_21862004160,870243567_56915814033_814203,step_1,2017-05-08 16:08:30,Test,5.0,5.0,0.07,10,124,31,F,3,107059.74,6,9,young/adult
305734,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,15.0,10.0,0.20,10,124,31,F,3,107059.74,6,9,young/adult
305735,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,54.0,39.0,0.72,10,124,31,F,3,107059.74,6,9,young/adult
305736,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,75.0,21.0,1.00,10,124,31,F,3,107059.74,6,9,young/adult

In [112]:
df_test_complete = df_complete_group[df_complete_group["treatment_group"] == "Test"]
df_test_complete["client_id"].nunique()

17853

In [113]:
df_control_complete = df_complete_group[df_complete_group["treatment_group"] == "Control"]
df_control_complete["client_id"].nunique()

14810

In [93]:
# test_complete_rate = round(df_test_complete.shape[0]/df_test.shape[0],2)
# control_complete_rate = round(len(df_control_complete)/len(df_control),2)
# test_complete_rate, control_complete_rate

(0.65, 0.66)

In [114]:
test_complete_rate = round(df_test_complete["client_id"].nunique()/df_test["client_id"].nunique(),2)
control_complete_rate = round(df_control_complete["client_id"].nunique()/df_control["client_id"].nunique(),2)
test_complete_rate, control_complete_rate

(0.7, 0.7)

Statistic

In [ ]:
stat,p_value = st.ttest_ind(df_test_stat[],df_control_stat[], equal_var=False, alternative="two-sided")

2. Time spent

In [122]:
stats_df1 = df_complete_group.copy()
stats_df1 = stats_df1[~((stats_df1["process_step"] == "confirm") & (stats_df1["time_diff"] == 0))]
stats_df1

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative,time_diff_percent,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,client_age_group
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0.0,0.0,0.00,3,46,29,U,2,25454.66,2,6,young/adult
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,7.0,7.0,0.04,3,46,29,U,2,25454.66,2,6,young/adult
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,39.0,32.0,0.25,3,46,29,U,2,25454.66,2,6,young/adult
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,138.0,99.0,0.87,3,46,29,U,2,25454.66,2,6,young/adult
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,158.0,20.0,1.00,3,46,29,U,2,25454.66,2,6,young/adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305732,9999729,834634258_21862004160,870243567_56915814033_814203,start,2017-05-08 16:08:25,Test,0.0,0.0,0.00,10,124,31,F,3,107059.74,6,9,young/adult
305733,9999729,834634258_21862004160,870243567_56915814033_814203,step_1,2017-05-08 16:08:30,Test,5.0,5.0,0.07,10,124,31,F,3,107059.74,6,9,young/adult
305734,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,15.0,10.0,0.20,10,124,31,F,3,107059.74,6,9,young/adult
305735,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,54.0,39.0,0.72,10,124,31,F,3,107059.74,6,9,young/adult
305736,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,75.0,21.0,1.00,10,124,31,F,3,107059.74,6,9,young/adult

In [117]:
# stats_df1 = stats_df1.groupby(['treatment_group', 'process_step'])['time_diff'].agg(["mean", "median",lambda x: list(x)]).round(2)
stats_df1 = stats_df1.groupby([ 'process_step','treatment_group',]).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df1

                              Average_Time_Diff  Median_Time_Diff  \
process_step treatment_group
confirm      Control                     414.06             280.0
             Test                        449.96             260.0
start        Control                     100.09               0.0
             Test                        105.57               0.0
step_1       Control                     141.31              29.0
             Test                        147.70              17.0
step_2       Control                     173.98              72.0
             Test                        197.56              65.0
step_3       Control                     271.53             170.0
             Test                        282.67             159.0

                                                                      Time_diff
process_step treatment_group
confirm      Control          [245.0, 95.0, 292.0, 90.0, 443.0, 227.0, 626.0...
             Test             [158.0, 377.0, 211.0, 954.0, 688.0, 223.0, 117...
start        Control          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 295.0, 0.0...
             Test             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0,...
step_1       Control          [33.0, 4.0, 13.0, 13.0, 11.0, 30.0, 330.0, 30....
             Test             [7.0, 7.0, 25.0, 56.0, 60.0, 121.0, 6.0, 105.0...
step_2       Control          [131.0, 10.0, 72.0, 52.0, 21.0, 44.0, 35.0, 37...
             Test             [39.0, 25.0, 51.0, 91.0, 76.0, 140.0, 33.0, 11...
step_3       Control          [162.0, 61.0, 78.0, 193.0, 38.0, 128.0, 99.0, ...
             Test             [138.0, 214.0, 102.0, 698.0, 658.0, 167.0, 60....

In [123]:
stats_df1_treatment = stats_df1.groupby([ 'process_step']).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df1_treatment

,Average_Time_Diff,Median_Time_Diff,Time_diff
process_step,,,
confirm,434.34,269.0,"[158.0, 377.0, 245.0, 95.0, 211.0, 954.0, 688...."
start,103.23,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
step_1,144.91,23.0,"[7.0, 7.0, 33.0, 4.0, 25.0, 56.0, 60.0, 121.0,..."
step_2,186.53,69.0,"[39.0, 25.0, 131.0, 10.0, 72.0, 51.0, 91.0, 76..."
step_3,277.39,164.0,"[138.0, 214.0, 162.0, 61.0, 78.0, 102.0, 698.0..."

In [118]:
stats_df2 = df_complete_group.copy()
stats_df2 = stats_df2.groupby([ 'process_step','treatment_group']).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df2 #Without filter confirm and 0 timediff and reach confirm

                              Average_Time_Diff  Median_Time_Diff  \
process_step treatment_group
confirm      Control                     414.06             280.0
             Test                        449.85             260.0
start        Control                     100.09               0.0
             Test                        105.57               0.0
step_1       Control                     141.31              29.0
             Test                        147.70              17.0
step_2       Control                     173.98              72.0
             Test                        197.56              65.0
step_3       Control                     271.53             170.0
             Test                        282.67             159.0

                                                                      Time_diff
process_step treatment_group
confirm      Control          [245.0, 95.0, 292.0, 90.0, 443.0, 227.0, 626.0...
             Test             [158.0, 377.0, 211.0, 954.0, 688.0, 223.0, 117...
start        Control          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 295.0, 0.0...
             Test             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.0,...
step_1       Control          [33.0, 4.0, 13.0, 13.0, 11.0, 30.0, 330.0, 30....
             Test             [7.0, 7.0, 25.0, 56.0, 60.0, 121.0, 6.0, 105.0...
step_2       Control          [131.0, 10.0, 72.0, 52.0, 21.0, 44.0, 35.0, 37...
             Test             [39.0, 25.0, 51.0, 91.0, 76.0, 140.0, 33.0, 11...
step_3       Control          [162.0, 61.0, 78.0, 193.0, 38.0, 128.0, 99.0, ...
             Test             [138.0, 214.0, 102.0, 698.0, 658.0, 167.0, 60....

In [124]:
stats_df2_treatment = df_complete_group.copy()
stats_df2_treatment = stats_df2_treatment.groupby([ 'process_step']).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df2_treatment

,Average_Time_Diff,Median_Time_Diff,Time_diff
process_step,,,
confirm,434.28,269.0,"[158.0, 377.0, 245.0, 95.0, 211.0, 954.0, 688...."
start,103.23,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
step_1,144.91,23.0,"[7.0, 7.0, 33.0, 4.0, 25.0, 56.0, 60.0, 121.0,..."
step_2,186.53,69.0,"[39.0, 25.0, 131.0, 10.0, 72.0, 51.0, 91.0, 76..."
step_3,277.39,164.0,"[138.0, 214.0, 162.0, 61.0, 78.0, 102.0, 698.0..."

In [119]:
stats_df3 = df_stat.copy()
stats_df3 = stats_df3.groupby([ 'process_step','treatment_group']).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df3

                              Average_Time_Diff  Median_Time_Diff  \
process_step treatment_group
confirm      Control                     407.52             273.0
             Test                        426.87             241.0
start        Control                     156.67               0.0
             Test                        168.66               0.0
step_1       Control                     147.50              31.0
             Test                        167.73              22.0
step_2       Control                     181.07              73.0
             Test                        217.12              75.0
step_3       Control                     280.72             172.0
             Test                        305.47             166.0

                                                                      Time_diff
process_step treatment_group
confirm      Control          [245.0, 95.0, 292.0, 90.0, 443.0, 227.0, 626.0...
             Test             [158.0, 377.0, 211.0, 0.0, 82.0, 954.0, 688.0,...
start        Control          [0.0, 0.0, 0.0, 0.0, 0.0, 804.0, 0.0, 0.0, 0.0...
             Test             [0.0, 0.0, 0.0, 32.0, 114.0, 142.0, 0.0, 0.0, ...
step_1       Control          [49.0, 112.0, 507.0, 527.0, 538.0, 11.0, 33.0,...
             Test             [7.0, 7.0, 25.0, 8.0, 206.0, 5.0, 112.0, 245.0...
step_2       Control          [121.0, 529.0, 22.0, 131.0, 10.0, 72.0, 120.0,...
             Test             [39.0, 25.0, 51.0, 213.0, 68.0, 149.0, 237.0, ...
step_3       Control          [396.0, 162.0, 61.0, 78.0, 574.0, 193.0, 38.0,...
             Test             [138.0, 214.0, 102.0, 262.0, 495.0, 698.0, 658...

In [125]:
stats_df3_treament = df_stat.copy()
stats_df3_treament = stats_df3_treament.groupby([ 'process_step']).agg( 
    Average_Time_Diff = ('time_diff',"mean"),
    Median_Time_Diff = ('time_diff',"median"),
    Time_diff = ('time_diff',lambda x: list(x))
).round(2)

stats_df3_treament

,Average_Time_Diff,Median_Time_Diff,Time_diff
process_step,,,
confirm,418.73,256.0,"[158.0, 377.0, 245.0, 95.0, 211.0, 0.0, 82.0, ..."
start,163.46,0.0,"[0.0, 0.0, 0.0, 32.0, 114.0, 142.0, 0.0, 0.0, ..."
step_1,158.97,27.0,"[7.0, 7.0, 49.0, 112.0, 507.0, 527.0, 538.0, 1..."
step_2,200.72,74.0,"[39.0, 25.0, 121.0, 529.0, 22.0, 131.0, 10.0, ..."
step_3,293.93,169.0,"[138.0, 214.0, 396.0, 162.0, 61.0, 78.0, 102.0..."

3. Error rate

In [120]:
df_error = df_stat.groupby(['client_id', 'visit_id', 'visitor_id']).apply(functions.calculate_error_rate).reset_index()

# Calculate avg error rate by treatment_group
avg_error_rates = df_error.groupby('treatment_group')['error_rate'].mean().reset_index()
avg_error_rates

C:\Users\Gast\AppData\Local\Temp\ipykernel_5600\2118302418.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_error = df_stat.groupby(['client_id', 'visit_id', 'visitor_id']).apply(functions.calculate_error_rate).reset_index()

  treatment_group  error_rate
0         Control    4.886170
1            Test    7.010189