In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
final_web_data=pd.read_csv('../data/raw/df_footprints.csv')

Reading the files

In [5]:
experiment_client=pd.read_csv('../data/raw/df_final_experiment_clients.txt')
# experiment_client

In [4]:
final_demo=pd.read_csv('../data/raw/df_final_demo.txt')
# final_demo

In [3]:
web_data_1=pd.read_csv('../data/raw/df_final_web_data_pt_1.txt')
# web_data_1

In [2]:
web_data_2=pd.read_csv('../data/raw/df_final_web_data_pt_2.txt')
# web_data_2

Concatenating and saving the files

In [6]:
final_web_data=pd.concat([web_data_1,web_data_2])
final_web_data=pd.merge(final_web_data, experiment_client, on='client_id', how = "left")
final_web_data
# final_web_data.to_csv('../data/raw/df_final_web_data_concat.csv')

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10,NaN
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29,NaN
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51,NaN
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34,NaN
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09,NaN

In [7]:
# final_demo=pd.merge(final_demo,experiment_client, on= 'client_id')
# final_demo=final_demo.drop('Variation_y',axis=1)
# final_demo= final_demo.rename(columns={"Variation_x":"variation"})
final_demo.to_csv('../data/raw/df_final_demo_concat.csv')
final_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

Understanding the data

In [9]:
final_web_data

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10,NaN
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29,NaN
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51,NaN
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34,NaN
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09,NaN

In [10]:
final_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [ ]:
final_demo['bal'].unique()

In [ ]:
final_web_data['Variation'].unique()

In [ ]:
final_web_data

In [ ]:
final_demo.info()

In [ ]:
Active=['Test', 'Control']
test=final_demo[final_demo['Variation'].isin(Active)]

In [ ]:
test= test[test['clnt_age']<35]
test['clnt_age'].count()

In [ ]:
sns.histplot(data=test['clnt_tenure_yr'], kde= True,legend=False, bins=10, color='Lightgreen')

In [ ]:
test['clnt_tenure_yr'].describe()

In [ ]:
# sns.histplot(data=test['clnt_age'], kde= True,legend=False, bins=10, color='Green')

# Checking the cleaned files

In [11]:
file1=pd.read_csv('../Data/clean/final_client_experiment_Cleaned.csv')
file1

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
317230,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
317231,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
317232,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
317233,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
317234,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [12]:
file2=pd.read_csv('../Data/clean/df_final_demo_concat_cleaned.csv')
file2

,client_id,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,variation
0,836976,6,73,60,U,2,45105.30,6,9,Test
1,2304905,7,94,58,U,2,110860.30,6,9,Control
2,1439522,5,64,32,U,2,52467.79,6,9,Test
3,1562045,16,198,49,M,2,67454.65,3,6,Test
4,5126305,12,145,33,F,2,103671.75,0,3,Control
...,...,...,...,...,...,...,...,...,...,...
50483,1780858,21,262,68,M,3,372100.59,6,9,Test
50484,6967120,21,260,68,M,3,4279873.38,6,9,Control
50485,5826160,20,249,56,F,2,44837.16,2,5,Test
50486,8739285,19,229,69,F,2,44994.24,1,4,Test
50487,7468138,18,222,61,F,3,209278.15,0,3,Test

In [ ]:
file3=pd.read_csv('../Data/clean/df_footprints_transformed_client_merged.csv')
file3

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative,time_diff_percent,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,treament_group
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0.0,0.0,0.00,3,46,29,U,2,25454.66,2,6,Test
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,7.0,7.0,0.04,3,46,29,U,2,25454.66,2,6,Test
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,39.0,32.0,0.25,3,46,29,U,2,25454.66,2,6,Test
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,138.0,99.0,0.87,3,46,29,U,2,25454.66,2,6,Test
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,158.0,20.0,1.00,3,46,29,U,2,25454.66,2,6,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305734,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,15.0,10.0,0.20,10,124,31,F,3,107059.74,6,9,Test
305735,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,54.0,39.0,0.72,10,124,31,F,3,107059.74,6,9,Test
305736,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,75.0,21.0,1.00,10,124,31,F,3,107059.74,6,9,Test
305737,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0.0,0.0,0.00,23,281,49,F,2,431887.61,1,4,Test
305738,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,8.0,8.0,1.00,23,281,49,F,2,431887.61,1,4,Test

In [13]:
personal=pd.merge(file2,file1, on= 'client_id')
personal

,client_id,client_tenure_year,client_tenure_month,client_age,gender,num_accts,balance,calls_6_mnth,logons_6_mnth,variation,visitor_id,visit_id,process_step,date_time,treatment_group
0,836976,6,73,60,U,2,45105.30,6,9,Test,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:51:13,Test
1,836976,6,73,60,U,2,45105.30,6,9,Test,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:47:50,Test
2,836976,6,73,60,U,2,45105.30,6,9,Test,427070339_1413275162,228976764_46825473280_96584,confirm,2017-04-02 11:46:45,Test
3,836976,6,73,60,U,2,45105.30,6,9,Test,427070339_1413275162,228976764_46825473280_96584,step_3,2017-04-02 11:23:08,Test
4,836976,6,73,60,U,2,45105.30,6,9,Test,427070339_1413275162,228976764_46825473280_96584,step_2,2017-04-02 11:22:24,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317130,7468138,18,222,61,F,3,209278.15,0,3,Test,317123960_46820919455,769876461_30381166055_830233,step_2,2017-03-30 23:59:15,Test
317131,7468138,18,222,61,F,3,209278.15,0,3,Test,317123960_46820919455,769876461_30381166055_830233,step_1,2017-03-30 23:58:51,Test
317132,7468138,18,222,61,F,3,209278.15,0,3,Test,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:58:40,Test
317133,7468138,18,222,61,F,3,209278.15,0,3,Test,317123960_46820919455,769876461_30381166055_830233,start,2017-03-30 23:55:11,Test
317134,7468138,18,222,61,F,3,209278.15,0,3,Test,317123960_46820919455,769876461_30381166055_830233,start,2017-03-31 00:16:12,Test