In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
file1=pd.read_csv('../Data/clean/final_client_experiment_Cleaned.csv')
file2=pd.read_csv('../Data/clean/df_final_demo_concat_cleaned.csv')

Filtering to get only the clients who finished all steps

In [4]:
Test=file1[file1['process_step']== "confirm"]['client_id'].unique()
clients_all_steps=file1[file1['client_id'].isin(Test)]

Filtering to get the ages specified in the hypotesis

In [5]:
clients_with_age=file2[['client_id','client_age']]

final_data_clients=pd.merge(clients_all_steps,clients_with_age,on='client_id', how = "left")

In [6]:
final_data_clients.columns

Index(['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time',
       'treatment_group', 'client_age'],
      dtype='object')

In [7]:
final_data_clients[final_data_clients['client_age'].isnull()]['client_id'].unique()

array([8191345, 5144725, 7616759, 5277910,  355337, 1227228, 1037867,
       8611797, 7402828, 4876926])

Adding the age to the missing clients with no age. equally divided between both groups

In [8]:
ids_no_age=pd.DataFrame(final_data_clients[final_data_clients['client_age'].isnull()]['client_id'].unique(), columns=['client_id'])
new_age={8191345: 34, 5144725: 34, 7616759:34, 5277910:34, 355337: 34, 1227228: 54, 1037867: 54, 8611797: 54, 7402828: 54,4876926:54}
ids_only=[8191345,5144725,7616759,5277910,355337,1227228,1037867,8611797,7402828,4876926]
mask = final_data_clients['client_id'].isin(ids_only)
final_data_clients.loc[mask,'client_age']=final_data_clients['client_id'].map(new_age)

In [9]:
final_data_clients.to_csv("../data/clean/Final_file.csv", index=False, encoding='utf-8')

In [10]:
final_data_clients[final_data_clients['process_step']== "confirm"]['client_id'].value_counts()

client_id
465007     19
1637369    17
8290360    17
8047921    17
6556668    16
           ..
2317698     1
8895190     1
5780472     1
3667184     1
2856801     1
Name: count, Length: 34121, dtype: int64

In [11]:
final_data_clients[final_data_clients['process_step']== "confirm"]['client_id'].count()

np.int64(42936)

In [12]:
final_data_clients[final_data_clients['process_step']== "confirm"]['client_id'].unique()

array([8320017, 4033851, 1982004, ..., 6426623,  433098, 1574008],
      shape=(34121,))

In [ ]:
final_data_clients['client_age'].describe()

          client_id     client_age
count  2.434180e+05  243418.000000
mean   5.008006e+06      47.433924
std    2.871200e+06      15.461833
min    5.550000e+02      17.000000
25%    2.515513e+06      34.000000
50%    5.055243e+06      49.000000
75%    7.466392e+06      60.000000
max    9.999729e+06      95.000000

Comparing the two groups age and tenure

In [16]:
raw=pd.read_csv('../Data/raw/df_final_demo_concat.csv')

C:\Users\jesus\AppData\Local\Temp\ipykernel_13864\621709890.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  raw=pd.read_csv('../Data/raw/df_final_demo_concat.csv')

In [17]:
raw.columns

Index(['Unnamed: 0', 'client_id', 'clnt_tenure_yr', 'clnt_tenure_mnth',
       'clnt_age', 'gendr', 'num_accts', 'bal', 'calls_6_mnth',
       'logons_6_mnth', 'variation'],
      dtype='object')

In [20]:
raw_control=raw[raw['variation']=='Control']

In [ ]:
raw_control.describe()

,Unnamed: 0,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,23532.000000,2.353200e+04,23527.000000,23527.000000,23526.000000,23527.000000,2.352700e+04,23527.000000,23527.000000
mean,25343.343787,5.013963e+06,12.087686,151.060186,47.498427,2.259914,1.501473e+05,3.129213,6.166277
std,14515.088728,2.877470e+06,6.877531,82.126443,15.521781,0.538559,2.958070e+05,2.184502,2.173014
min,1.000000,1.028000e+03,2.000000,33.000000,17.000000,2.000000,2.378961e+04,0.000000,3.000000
25%,12824.750000,2.515401e+06,6.000000,82.000000,33.500000,2.000000,4.012335e+04,1.000000,4.000000
50%,25381.500000,5.023892e+06,11.000000,137.000000,48.500000,2.000000,6.602418e+04,3.000000,6.000000
75%,37846.000000,7.483811e+06,16.000000,192.000000,60.000000,2.000000,1.406060e+05,5.000000,8.000000
max,50496.000000,9.998921e+06,55.000000,669.000000,96.000000,7.000000,8.292996e+06,6.000000,9.000000

In [22]:
raw_test=raw[raw['variation']=='Test']

In [23]:
raw_test.describe()

,Unnamed: 0,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,26968.000000,2.696800e+04,26961.000000,26961.000000,26961.000000,26961.000000,2.696100e+04,26961.000000,26961.000000
mean,25167.612875,4.999386e+06,11.982901,149.852899,47.163922,2.249917,1.489626e+05,3.061941,6.101851
std,14632.897212,2.877455e+06,6.844947,81.783390,15.514461,0.529335,3.073737e+05,2.190590,2.177119
min,0.000000,5.550000e+02,2.000000,33.000000,17.000000,1.000000,2.378944e+04,0.000000,3.000000
25%,12450.250000,2.516165e+06,6.000000,82.000000,33.500000,2.000000,3.972920e+04,1.000000,4.000000
50%,25136.000000,5.025620e+06,11.000000,134.000000,47.500000,2.000000,6.546836e+04,3.000000,6.000000
75%,37902.500000,7.469167e+06,15.000000,191.000000,59.500000,2.000000,1.394786e+05,5.000000,8.000000
max,50499.000000,9.999832e+06,55.000000,669.000000,96.000000,7.000000,1.632004e+07,6.000000,9.000000

Defining for how long they ran the experiment

In [28]:
final1=pd.read_csv('../Data/clean/final_file.csv')
final1

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,client_age
0,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05,Test,34.0
1,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43,Test,34.0
2,8320017,39393514_33118319366,960651974_70596002104_312201,step_2,2017-04-05 13:08:40,Test,34.0
3,8320017,39393514_33118319366,960651974_70596002104_312201,step_1,2017-04-05 13:08:24,Test,34.0
4,8320017,39393514_33118319366,960651974_70596002104_312201,start,2017-04-05 13:08:06,Test,34.0
...,...,...,...,...,...,...,...
243413,1574008,117364417_77840596075,528720790_71583064618_169151,confirm,2017-05-06 23:51:05,Test,55.0
243414,1574008,117364417_77840596075,528720790_71583064618_169151,step_3,2017-05-06 23:50:40,Test,55.0
243415,1574008,117364417_77840596075,528720790_71583064618_169151,step_2,2017-05-06 23:43:47,Test,55.0
243416,1574008,117364417_77840596075,528720790_71583064618_169151,step_1,2017-05-06 23:43:34,Test,55.0
243417,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test,55.0

In [84]:
final2=pd.read_csv('../Data/clean/df_footprints_transformed.csv')
final2

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0 days 00:00:00,0 days 00:00:00
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,0 days 00:00:07,0 days 00:00:07
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,0 days 00:00:39,0 days 00:00:32
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,0 days 00:02:18,0 days 00:01:39
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,0 days 00:02:38,0 days 00:00:20
...,...,...,...,...,...,...,...,...
305832,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,0 days 00:00:15,0 days 00:00:10
305833,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,0 days 00:00:54,0 days 00:00:39
305834,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,0 days 00:01:15,0 days 00:00:21
305835,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0 days 00:00:00,0 days 00:00:00
305836,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,0 days 00:00:08,0 days 00:00:08

In [87]:
final2

,client_id,visitor_id,visit_id,process_step,date_time,treatment_group,time_diff,time_diff_relative
0,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0 days 00:00:00,0 days 00:00:00
1,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,0 days 00:00:07,0 days 00:00:07
2,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,0 days 00:00:39,0 days 00:00:32
3,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,0 days 00:02:18,0 days 00:01:39
4,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,0 days 00:02:38,0 days 00:00:20
...,...,...,...,...,...,...,...,...
305832,9999729,834634258_21862004160,870243567_56915814033_814203,step_2,2017-05-08 16:08:40,Test,0 days 00:00:15,0 days 00:00:10
305833,9999729,834634258_21862004160,870243567_56915814033_814203,step_3,2017-05-08 16:09:19,Test,0 days 00:00:54,0 days 00:00:39
305834,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,0 days 00:01:15,0 days 00:00:21
305835,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0 days 00:00:00,0 days 00:00:00
305836,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,0 days 00:00:08,0 days 00:00:08

In [30]:
final1['date_time'].min()

'2017-03-15 00:19:28'

In [26]:
final1['date_time'].max()

'2017-06-20 23:26:00'

In [41]:
foot=pd.read_csv('../Data/clean/df_footprints_transformed.csv')

Calculating the Completion Rate

In [ ]:
final_file=pd.read_csv('../Data/clean/df_footprints_transformed_client_merged.csv')
final_file

In [30]:
final_file[(final_file['treatment_group']=='Test')]['client_id'].nunique()

25439

In [32]:
confirm_test=final_file[(final_file['process_step']=="confirm") & (final_file['treatment_group']=='Test') & (final_file['time_diff']!= 0)]
confirm_test['client_id'].nunique()

18492

In [33]:
final_file[(final_file['treatment_group']=='Control')]['client_id'].nunique()

21112

In [34]:
confirm_Control=final_file[(final_file['process_step']=="confirm") & (final_file['treatment_group']=='Control') & (final_file['time_diff']!= '0 days 00:00:00')]
confirm_Control['client_id'].nunique()

15326